name: BuildAndDeploy

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for Docker Image'
        required: true
        type: string
        default: 'latest'

jobs:
  dockerCI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            mrszcz/webapp:latest
            mrszcz/webapp:${{ inputs.tag }}

  kubernetesCI:
    runs-on: ubuntu-latest
    needs: dockerCI
    steps:
      - name: Checkout Config Repository
        uses: actions/checkout@v4
        with:
          repository: MrSzcz/Config_Repo
          path: Config_Repo

     - name: Git Safe Dirrectory
       run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Configure Git
        run: |
          git config user.email "kacper.szczepaniuk@pollub.edu.pl"
          git config user.name "mrszcz"

      - name: Update Manifests
        run: |
          sed -i "s/webapp:.*/webapp:${{ inputs.tag }}/g" deployment.yaml

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Update image reference"
          git push


